name: Multiverse-Portals
main: org.mvplugins.multiverse.portals.MultiversePortals
authors: ['Rigby', 'fernferret', 'benwoo1110']
version: ${version}
api-version: 1.13
depend: ['Multiverse-Core']
softdepend: ['WorldEdit']
