name: 'PR: Require Label'

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches: [main]

jobs:
  require_label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "release:major, release:minor, release:patch, no release"
